import { expect } from 'chai';
import { compile } from '../../src/compiler/index.js';

const text = `
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[Aegisub Project Garbage]

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,text
`;

describe('ASS compiler', () => {
  it('should compile ASS', () => {
    const { info, width, height, collisions, styles, dialogues } = compile(text);
    expect(info).to.deep.equal({
      Title: 'Default Aegisub file',
      ScriptType: 'v4.00+',
      WrapStyle: '0',
      ScaledBorderAndShadow: 'yes',
      'YCbCr Matrix': 'None',
    });
    expect(width).to.equal(null);
    expect(height).to.equal(null);
    expect(collisions).to.equal('Normal');
    expect(styles).to.have.property('Default');
    expect(dialogues).to.be.lengthOf(1);
  });
});
